// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKM14kC-sbZ-Ueh27QRnffY7oGqONHz0M',
    appId: '1:35812697066:web:de3b3a7184ef87dab18893',
    messagingSenderId: '35812697066',
    projectId: 'omnicart-e5225',
    authDomain: 'omnicart-e5225.firebaseapp.com',
    storageBucket: 'omnicart-e5225.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN5YcGpeNYno5kWbbedAPSBixR84s1Xgk',
    appId: '1:35812697066:android:e8381ee9488ee1a5b18893',
    messagingSenderId: '35812697066',
    projectId: 'omnicart-e5225',
    storageBucket: 'omnicart-e5225.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_njxnSdGBw_Wu0fUtndeovRwjs-L15w',
    appId: '1:35812697066:ios:be332bc608c5aa91b18893',
    messagingSenderId: '35812697066',
    projectId: 'omnicart-e5225',
    storageBucket: 'omnicart-e5225.firebasestorage.app',
    iosBundleId: 'com.example.omnicart',
  );
}
